/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.weekbach9to11;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class PracticeTable extends javax.swing.JFrame {
        SingletonClass conn = SingletonClass.getInstance();
    ArrayList<StudentModel> studentList = new ArrayList<>();

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PracticeTable.class.getName());

    /**
     * Creates new form PracticeTable
     */
    public PracticeTable() {
        initComponents();
        getData();
        Color color = new Color(0,102,102);
       practiceTable.getTableHeader().setBackground(color);
        practiceTable.getTableHeader().setForeground(color.white);
        practiceTable.setRowHeight(30);
        
        
    }
    void getData(){
     String header[] = {"Id","Email","Password"};
     
     DefaultTableModel obj = new DefaultTableModel(null, header);
     practiceTable.setModel(obj);
     obj.setRowCount(0);
     studentList.clear();
     
     try{
         
         String query = "SELECT * FROM registeredtable";
         Statement state  = conn.connection.createStatement();
         ResultSet result = state.executeQuery(query);
         
         while(result.next()){
             studentList.add(new StudentModel(result.getInt("id"),result.getString("email"),result.getString("password")));
         }
         Object[] row = new Object[3];
         for(StudentModel item: studentList){
            row[0] = item.getId();
            row[1] = item.getEmail();
            row[2] =item.getPass();
            obj.addRow(row);
         }
         
         
     
     }catch(SQLException exception){
     System.out.println("Check Exception: "+exception);
     }
     
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        practiceTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        practiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        practiceTable.setRowHeight(30);
        practiceTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        practiceTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        practiceTable.setShowHorizontalLines(true);
        practiceTable.getTableHeader().setReorderingAllowed(false);
        practiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                practiceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(practiceTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void practiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceTableMouseClicked
        // TODO add your handling code here:
        int row = practiceTable.getSelectedRow();
        Object value = practiceTable.getValueAt(row, 0);
        int selectedId = Integer.parseInt(value.toString());
        
        System.out.println("Clicked");
       int choice =  JOptionPane.showConfirmDialog(this, "Update or Delete","Confirm Action", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION){
            
         // Update
        }else{
           String deleteQuery = "DELETE FROM registeredtable WHERE ID=?";
           
           try{
               PreparedStatement ps = conn.connection.prepareCall(deleteQuery);
               ps.setInt(1, selectedId);
               if(ps.executeUpdate() > 0){
                  
                JOptionPane.showMessageDialog(this, "Message Deleted");
                 getData();
               }
            
               
               
           }catch(SQLException exception){
            System.out.println("Delete Exception: "+exception);
        }
        }       
       
        
    }//GEN-LAST:event_practiceTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PracticeTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable practiceTable;
    // End of variables declaration//GEN-END:variables
}
