/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.weekbach9to11;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class StudentTable extends javax.swing.JFrame {
    SingletonClass conn = SingletonClass.getInstance();
    
    ArrayList<StudentModel> studentList = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentTable.class.getName());

    /**
     * Creates new form StudentTable
     */
    public StudentTable() {
        initComponents();
        getStudent();
    }

    void getStudent(){
//        studentList.add(new StudentModel("Vishal","vishal@gmail.com","123456"));
//        studentList.add(new StudentModel("Yuvraj","yuvraj@gmail.com","123123"));
//        studentList.add(new StudentModel("Sunny","sunny@gmail.com","123466"));
//        studentList.add(new StudentModel("Abhinandan","abhinandan@gmail.com","123466"));
//        studentList.add(new StudentModel("Sayam","sayam@gmail.com","123666"));

       String getData = "SELECT * FROM registeredtable";
        
        String header[] = {"Id","Email","Password"};
        
        Statement state;
        try {
            state = conn.connection.createStatement();
            ResultSet result  = state.executeQuery(getData);
        
        DefaultTableModel model = new DefaultTableModel(null,header);
        studentTable.setModel(model);
        model.setRowCount(0);
        
        while(result.next()){
            studentList.add(new StudentModel(result.getInt("id"),result.getString("email"), result.getString("password")));
        
        }
        
        
        Object[] row = new Object[3];
        for(StudentModel item: studentList){
            row[0] = item.getId();
            row[1] = item.getEmail();
            row[2] = item.getPass();
            model.addRow(row);
        }
        } catch (SQLException ex) {
            System.getLogger(StudentTable.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studentTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentTable.setRowHeight(30);
        studentTable.setSelectionBackground(new java.awt.Color(255, 102, 102));
        studentTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        studentTable.setShowHorizontalLines(true);
        studentTable.getTableHeader().setReorderingAllowed(false);
        studentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentTableMouseClicked
        // TODO add your handling code here:
       int row = studentTable.getSelectedRow();
       if(row >= 0){
       Object value = studentTable.getValueAt(row,0);
        int selectId = Integer.parseInt(value.toString());
        System.out.println("Selected Id:"+selectId);
        FormScreen screen = new FormScreen(selectId);
        screen.setVisible(true);
       }
    }//GEN-LAST:event_studentTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentTable().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
